//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB84.M3U.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB84.M3U.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EXTM3U
        ///#EXTINF:-1 tvg-name=&quot;Das Erste HD&quot; tvg-id=&quot;DasErste.de&quot; group-title=&quot;IPTV-DE&quot; tvg-logo=&quot;https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/daserstehd.png&quot;,Das Erste HD
        ///https://daserste-live.ard-mcdn.de/daserste/live/hls/de/master.m3u8
        ///#EXTINF:-1 tvg-name=&quot;ZDF HD&quot; tvg-id=&quot;ZDF.de&quot; group-title=&quot;IPTV-DE&quot; tvg-logo=&quot;https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/zdfhd.png&quot;,ZDF HD
        ///https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8
        ///#EXT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IPTVM3U {
            get {
                return ResourceManager.GetString("IPTVM3U", resourceCulture);
            }
        }
    }
}
